---
- name: Uninstall Tomcat and its dependencies
  hosts: web
  become: yes
  vars:
    req_java: java-1.8.0-openjdk
    req_tomcat_ver: 10.1.15
    tomcat_install_dir: "/usr/local/apache-tomcat-{{ req_tomcat_ver }}"
    tomcat_symlink_dir: /usr/local/latest
  tasks:
    - name: Stop Tomcat service
      shell: pkill -f 'org.apache.catalina.startup.Bootstrap'
      ignore_errors: yes

    - name: Remove Tomcat symlink directory
      file:
        path: "{{ tomcat_symlink_dir }}"
        state: absent

    - name: Remove Tomcat installation directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: absent

    - name: Uninstall Java
      yum:
        name: "{{ req_java }}"
        state: absent
