---
- name: simple usage of inline conditional statement ( if else)
  hosts: db
  gather_facts: true
  vars:
    x: 155
    y: 19
  tasks:
    - debug:
        msg: "The larger number of {{x}} and {{y}} is: {{ x if ( x > y) else (y)}}"

- name: simple usage of inline conditional statement ( if else)
  hosts: web
  gather_facts: true
  vars:
    x: 155
    y: 19
    larger: "{{ x if ( x > y) else (y)}}"
  tasks:
    - debug:
        msg: "The larger number of {{x}} and {{y}} is: {{larger}}"
